#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}================================${NC}"
echo -e "${CYAN}  Mailcow 安全部署脚本${NC}"
echo -e "${CYAN}================================${NC}"
echo ""

if ! command -v docker &> /dev/null; then
    echo -e "${RED}错误: 未安装 Docker${NC}"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo -e "${RED}错误: 未安装 Docker Compose${NC}"
    exit 1
fi

# 生成随机密码
rand_pass() {
    python3 -c "import secrets,string; print(''.join(secrets.choice(string.ascii_letters+string.digits) for _ in range($1)))" 2>/dev/null \
    || cat /dev/urandom | tr -dc 'A-Za-z0-9' 2>/dev/null | head -c "$1"
}

# 如果 mailcow.conf 不存在，询问域名后自动生成
if [ ! -f mailcow.conf ]; then
    echo -e "${YELLOW}mailcow.conf 不存在，将自动生成配置${NC}"
    echo ""

    echo -e "${YELLOW}请输入你的邮件服务器域名 (FQDN)${NC}"
    echo -e "${CYAN}例如: mail.example.com${NC}"
    echo ""

    DOMAIN_REGEX='^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$'
    while true; do
        read -p "域名: " DOMAIN
        if [[ -z "$DOMAIN" ]]; then
            echo -e "${RED}域名不能为空！${NC}"
            continue
        fi
        if [[ ! "$DOMAIN" =~ $DOMAIN_REGEX ]]; then
            echo -e "${RED}请输入有效的域名 (如 mail.example.com)${NC}"
            continue
        fi
        break
    done

    echo ""
    echo -e "${GREEN}你输入的域名: ${CYAN}${DOMAIN}${NC}"
    read -p "确认? [Y/n] " confirm
    if [[ "$confirm" =~ ^[nN] ]]; then
        echo "已取消"
        exit 0
    fi

    # 检测时区
    if [ -f /etc/timezone ]; then
        TZ=$(cat /etc/timezone)
    elif [ -L /etc/localtime ]; then
        TZ=$(readlink /etc/localtime | sed -n 's|^.*zoneinfo/||p')
    fi
    TZ=${TZ:-Asia/Shanghai}

    echo -e "${YELLOW}正在生成安全配置...${NC}"

    DBPASS=$(rand_pass 28)
    DBROOT=$(rand_pass 28)
    REDISPASS=$(rand_pass 28)
    SOGO_KEY=$(rand_pass 16)

    cat > mailcow.conf << EOF
# Mailcow Configuration - Generated by deploy.sh
MAILCOW_HOSTNAME=${DOMAIN}
MAILCOW_PASS_SCHEME=BLF-CRYPT

DBNAME=mailcow
DBUSER=mailcow
DBPASS=${DBPASS}
DBROOT=${DBROOT}

REDISPASS=${REDISPASS}

HTTP_PORT=80
HTTP_BIND=
HTTPS_PORT=443
HTTPS_BIND=
HTTP_REDIRECT=y

SMTP_PORT=25
SMTPS_PORT=465
SUBMISSION_PORT=587
IMAP_PORT=143
IMAPS_PORT=993
POP_PORT=110
POPS_PORT=995
SIEVE_PORT=4190
DOVEADM_PORT=127.0.0.1:19991
SQL_PORT=127.0.0.1:13306
REDIS_PORT=127.0.0.1:7654

TZ=${TZ}
COMPOSE_PROJECT_NAME=mailcowdockerized
DOCKER_COMPOSE_VERSION=native
ACL_ANYONE=disallow
MAILDIR_GC_TIME=7200
ADDITIONAL_SAN=
AUTODISCOVER_SAN=y
ADDITIONAL_SERVER_NAMES=
SKIP_LETS_ENCRYPT=n
ACME_DNS_CHALLENGE=n
ACME_DNS_PROVIDER=dns_xxx
ACME_ACCOUNT_EMAIL=me@example.com
ENABLE_SSL_SNI=n
SKIP_IP_CHECK=n
SKIP_HTTP_VERIFICATION=n
SKIP_UNBOUND_HEALTHCHECK=n
SKIP_CLAMD=n
SKIP_OLEFY=n
SKIP_SOGO=n
SKIP_FTS=n
FTS_HEAP=128
FTS_PROCS=1
ALLOW_ADMIN_EMAIL_LOGIN=n
USE_WATCHDOG=y
WATCHDOG_NOTIFY_BAN=n
WATCHDOG_NOTIFY_START=y
WATCHDOG_EXTERNAL_CHECKS=n
WATCHDOG_VERBOSE=n
LOG_LINES=9999
IPV4_NETWORK=172.22.1
IPV6_NETWORK=fd4d:6169:6c63:6f77::/64
MAILDIR_SUB=Maildir
SOGO_EXPIRE_SESSION=480
SOGO_URL_ENCRYPTION_KEY=${SOGO_KEY}
DOVECOT_MASTER_USER=
DOVECOT_MASTER_PASS=
WEBAUTHN_ONLY_TRUSTED_VENDORS=n
SPAMHAUS_DQS_KEY=
ENABLE_IPV6=true
DISABLE_NETFILTER_ISOLATION_RULE=n
EOF

    chmod 600 mailcow.conf
    echo -e "${GREEN}mailcow.conf 已生成${NC}"

else
    # mailcow.conf 已存在，检查配置项
    if ! grep -q '^MAILCOW_HOSTNAME=' mailcow.conf; then
        echo -e "${RED}错误: mailcow.conf 中未找到 MAILCOW_HOSTNAME 配置项${NC}"
        exit 1
    fi

    echo -e "${YELLOW}请输入你的邮件服务器域名 (FQDN)${NC}"
    echo -e "${CYAN}例如: mail.example.com${NC}"
    echo ""

    DOMAIN_REGEX='^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$'
    while true; do
        read -p "域名: " DOMAIN
        if [[ -z "$DOMAIN" ]]; then
            echo -e "${RED}域名不能为空！${NC}"
            continue
        fi
        if [[ ! "$DOMAIN" =~ $DOMAIN_REGEX ]]; then
            echo -e "${RED}请输入有效的域名 (如 mail.example.com)${NC}"
            continue
        fi
        break
    done

    echo ""
    echo -e "${GREEN}你输入的域名: ${CYAN}${DOMAIN}${NC}"
    read -p "确认? [Y/n] " confirm
    if [[ "$confirm" =~ ^[nN] ]]; then
        echo "已取消"
        exit 0
    fi

    ESCAPED_DOMAIN=$(printf '%s\n' "$DOMAIN" | sed 's/[&/\]/\\&/g')

    echo -e "${YELLOW}正在配置 mailcow.conf...${NC}"
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s|^MAILCOW_HOSTNAME=.*|MAILCOW_HOSTNAME=${ESCAPED_DOMAIN}|g" mailcow.conf
    else
        sed -i "s|^MAILCOW_HOSTNAME=.*|MAILCOW_HOSTNAME=${ESCAPED_DOMAIN}|g" mailcow.conf
    fi
fi

# 同步 .env
if ! cp mailcow.conf .env; then
    echo -e "${RED}警告: 无法将 mailcow.conf 复制为 .env，请手动复制${NC}"
    echo -e "${YELLOW}运行: cp mailcow.conf .env${NC}"
fi

echo -e "${GREEN}配置完成！${NC}"
echo ""
echo -e "${CYAN}================================${NC}"
echo -e "${CYAN}  配置摘要${NC}"
echo -e "${CYAN}================================${NC}"
echo -e "  主机名: ${GREEN}${DOMAIN}${NC}"
echo -e "  HTTPS:  ${GREEN}https://${DOMAIN}:443${NC}"
echo -e "  Admin:  ${GREEN}admin${NC} / ${CYAN}moohoo${NC}"
echo -e "  ${YELLOW}(首次登录后请立即修改默认密码!)${NC}"
echo ""

read -p "是否现在启动 Mailcow? [Y/n] " start
if [[ ! "$start" =~ ^[nN] ]]; then
    echo -e "${YELLOW}正在启动 Mailcow...${NC}"
    docker compose up -d
    echo ""
    echo -e "${GREEN}Mailcow 已启动！${NC}"
    echo -e "访问 ${CYAN}https://${DOMAIN}${NC} 进行管理"
else
    echo -e "${YELLOW}稍后手动启动: docker compose up -d${NC}"
fi
